# this file would go here: ~/.config/snakemake/slurm/config.yaml
cluster:
    mkdir -p slurm-logs &&
    if [ -z {wildcards} ]; then log_wildcard=""; else log_wildcard=$(echo "-{wildcards}" | sed 's/ID=//'); fi  &&
    sbatch --mem={resources.mem_mb} -c {resources.cpus} -J {rule} -o slurm-logs/{rule}${{log_wildcard}}-%j.log -e slurm-logs/{rule}${{log_wildcard}}-%j.log --parsable
use-conda:
    True
conda-prefix:
    ${{CONDA_PREFIX}}/envs
cores:
    50
jobs:
    10
printshellcmds:
    True
reason:
    True
rerun-incomplete:
    True
scheduler:
    greedy
latency-wait:
    120
default-resources:
    - cpus=1
    - mem_mb=6000
cluster-cancel:
    scancel
