#!/usr/bin/env bash

if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
  printf "\n  Currently pulls Illumina amplicon workflow from:\n  github.com/asaravia-butler/GeneLab_Data_Processing/tree/mikes-branch/Amplicon/Illumina\n\n"
  printf "  For version info run \`GL-version\`.\n\n"
  exit
fi

curl -sLO https://github.com/asaravia-butler/GeneLab_Data_Processing/archive/refs/heads/mikes-branch.zip

unzip -qq mikes-branch.zip "GeneLab_Data_Processing-mikes-branch/Amplicon/Illumina/workflow-template/*"

mv GeneLab_Data_Processing-mikes-branch/Amplicon/Illumina/workflow-template/ .

rm -rf GeneLab_Data_Processing-mikes-branch/ mikes-branch.zip

printf "\n  Pulled Illumina amplicon workflow from:\n"
printf "    github.com/asaravia-butler/GeneLab_Data_Processing/tree/mikes-branch/Amplicon/Illumina\n\n"
