#!/usr/bin/env bash

if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    printf "\n  Currently pulls the kraken2 human reference database built as described here:\n"
    printf "      https://github.com/asaravia-butler/GeneLab_Data_Processing/blob/mikes-branch/Metagenomics/Remove_human_reads_from_raw_data/workflow-usage.md#reference-database-info\n"
    printf "\n  It is 3GB compressed, and ~4.3GB uncompressed.\n"
    printf "\n  For version info run \`GL-version\`.\n\n"
    exit
fi

printf "\n    Downloading reference database (3GB compressed):\n\n"
curl -L -o kraken2-human-db.tar.gz https://ndownloader.figshare.com/files/25627058
printf "\n"

printf "\n    Unpacking and decompressing (~4.3GB uncompressed)...\n"
tar -xzf kraken2-human-db.tar.gz

printf "\n  Pulled kraken2 human reference database built as described here:\n"
printf "      https://github.com/asaravia-butler/GeneLab_Data_Processing/blob/mikes-branch/Metagenomics/Remove_human_reads_from_raw_data/workflow-usage.md#reference-database-info\n\n"
