#!/usr/bin/env bash

if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    printf "\n  Downloads paired-end Illumina amplicon data for two test samples (~300 KB total) from:\n"
    printf "      https://figshare.com/articles/dataset/Illumina_amplicon_test_data/16725424\n\n"
    printf "  For version info run \`GL-version\`.\n\n"
    exit
fi

printf "\n    Downloading Sample-1 read files:\n\n"
curl -L -o Sample-1_R1_raw.fastq.gz https://figshare.com/ndownloader/files/30963532
curl -L -o Sample-1_R2_raw.fastq.gz https://figshare.com/ndownloader/files/30963535

printf "\n\n    Downloading Sample-2 read files:\n\n"
curl -L -o Sample-2_R1_raw.fastq.gz https://figshare.com/ndownloader/files/30963538
curl -L -o Sample-2_R2_raw.fastq.gz https://figshare.com/ndownloader/files/30963541

printf "\n\n  Pulled raw Illumina reads for two test samples from here:\n"
printf "      https://figshare.com/articles/dataset/Illumina_amplicon_test_data/16725424\n\n"

printf "  If using these with the Illumina amplicon workflow, don't forget to put them\n"
printf "      in the appropriate directory as set in the config.yaml file, and to add their \n"
printf "      names to the input sample ID file being used :)\n\n\n"
